[package]
name = "run"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
open = "1"
colored = "2"
sysinfo = "0.20.0"
sys-info = "0.9"
num_cpus = "0.2"